### ISSUE TITLE
Propagate errors in run_task & raise exception instead of exiting

### ISSUE THREAD

**Issue by Rizato** [polyswarm/polyswarm-client#51]
**Is your feature request related to a problem? Please describe.**
Client.run_task does not propagate errors up to asyncio & Client.run.
This means that asyncio will fail, but the run function never completes.

**Describe the solution you'd like**
First, the errors should propagate.
Second, instead of `sys.exit` it should raise a custom exception so the library users can choose how to react to errors.

**Describe alternatives you've considered**
calling os._exit and force quitting so they have no choice.

**Additional context**
https://github.com/polyswarm/polyswarm-client/blob/master/src/polyswarmclient/__init__.py#L154

```
consumer_1    | ERROR:asyncio:Task exception was never retrieved
consumer_1    | future: <Task finished coro=<Client.run_task() done, defined at /usr/local/lib/python3.5/site-packages/polyswarmclient/__init__.py:120> exception=ConnectionClosed('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason',)>
consumer_1    | Traceback (most recent call last):
consumer_1    |   File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 528, in transfer_data
consumer_1    |     msg = yield from self.read_message()
consumer_1    |   File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 580, in read_message
consumer_1    |     frame = yield from self.read_data_frame(max_size=self.max_size)
consumer_1    |   File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 645, in read_data_frame
consumer_1    |     frame = yield from self.read_frame(max_size)
consumer_1    |   File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 710, in read_frame
consumer_1    |     extensions=self.extensions,
consumer_1    |   File "/usr/local/lib/python3.5/site-packages/websockets/framing.py", line 100, in read
consumer_1    |     data = yield from reader(2)
consumer_1    |   File "/usr/local/lib/python3.5/asyncio/streams.py", line 666, in readexactly
consumer_1    |     raise IncompleteReadError(incomplete, n)
consumer_1    | asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
consumer_1    |
consumer_1    | The above exception was the direct cause of the following exception:
consumer_1    |
consumer_1    | Traceback (most recent call last):
consumer_1    |   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 242, in _step
consumer_1    |     result = coro.throw(exc)
consumer_1    |   File "/usr/local/lib/python3.5/site-packages/polyswarmclient/__init__.py", line 138, in run_task
consumer_1    |     await asyncio.gather(*[self.listen_for_events(chain) for chain in chains])
consumer_1    |   File "/usr/local/lib/python3.5/asyncio/futures.py", line 381, in __iter__
consumer_1    |     yield self  # This tells Task to wait for completion.
consumer_1    |   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
consumer_1    |     future.result()
consumer_1    |   File "/usr/local/lib/python3.5/asyncio/futures.py", line 294, in result
consumer_1    |     raise self._exception
consumer_1    |   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 240, in _step
consumer_1    |     result = coro.send(None)
consumer_1    |   File "/usr/local/lib/python3.5/site-packages/polyswarmclient/__init__.py", line 393, in listen_for_events
consumer_1    |     event = json.loads(await ws.recv())
consumer_1    |   File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 350, in recv
consumer_1    |     yield from self.ensure_open()
consumer_1    |   File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 501, in ensure_open
consumer_1    |     self.close_code, self.close_reason) from self.transfer_data_exc
consumer_1    | websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
consumer_1    | ERROR:root:Detected unhandled exception, exiting with failure
consumer_1    | ERROR:root:Ambassador exited. Closing endpoint.
```

**Comment by Rizato** [comment]
I see now that the output is intentional per https://github.com/polyswarm/polyswarm-client/blob/master/src/polyswarmclient/__init__.py#L132.

**Comment by mjkoo** [comment]
If invoked via run it does install a top-level exception handler which will exit, this is due to typically wanting to restart the container when things get kicked in infrastructure and was discussed prior to https://github.com/polyswarm/polyswarm-client/pull/31 in slack. You should be able to use run_task instead of run and get the behavior you want (part of the reason that is public). If not, we should take a look at that.

Given the above, what is the desired resolution here?

**Comment by myhndl** [comment]
Do we have a means for `polyswarm-client` to differentiate `polyswarmd` network connectivity failure and `polyswarmd` state reset (e.g. in the case of restart)?

This seems like desirable information because it allows us to:
1. in the case of network issues, re-establish websocket
2. in the case of restart, re-establish websocket and re-register callbacks

I believe we previously discussed sending a unique `polyswarmd` instance ID in the first message delivered over a websocket.

**Comment by myhndl** [comment]
Currently exiting here: https://github.com/polyswarm/polyswarm-client/blob/a77cd74fe32947e811103a6967fd154574c873b7/src/polyswarmclient/__init__.py#L146

New design, copied from Slack:
```
I'd like to more to re-establishing websocket instead for two reasons:
1. it'll make it slightly easier to track down issues in testnet - less container turnover. containers turning over should be more explicit.
2. users of polyswarm-client almost certainly don't want to exit in such a case. then they stop making money.
```

For item #1, i'm applying the reliability label.

**Comment by myhndl** [comment]
related: https://github.com/polyswarm/polyswarm-client/issues/70
